// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cSQMOjqqM7TRxFDqmrGuI8p5zmoIGxA',
    appId: '1:378073881524:web:085c7819653bf9f64d30e1',
    messagingSenderId: '378073881524',
    projectId: 'tanam-urban',
    authDomain: 'tanam-urban.firebaseapp.com',
    databaseURL: 'https://tanam-urban-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanam-urban.firebasestorage.app',
    measurementId: 'G-SW1S5W5064',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXAc5xj52rVCO4LImT5uDS_mPd4wGdEk',
    appId: '1:378073881524:android:e6eb5ac0e6e444224d30e1',
    messagingSenderId: '378073881524',
    projectId: 'tanam-urban',
    databaseURL: 'https://tanam-urban-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanam-urban.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0MD_cf0coQT7plno_xcW16A52v1U6g1o',
    appId: '1:378073881524:ios:fdceb241746cab194d30e1',
    messagingSenderId: '378073881524',
    projectId: 'tanam-urban',
    databaseURL: 'https://tanam-urban-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanam-urban.firebasestorage.app',
    iosBundleId: 'com.example.proyekTanamUrban',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0MD_cf0coQT7plno_xcW16A52v1U6g1o',
    appId: '1:378073881524:ios:fdceb241746cab194d30e1',
    messagingSenderId: '378073881524',
    projectId: 'tanam-urban',
    databaseURL: 'https://tanam-urban-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanam-urban.firebasestorage.app',
    iosBundleId: 'com.example.proyekTanamUrban',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cSQMOjqqM7TRxFDqmrGuI8p5zmoIGxA',
    appId: '1:378073881524:web:32e4ff723fb5a8684d30e1',
    messagingSenderId: '378073881524',
    projectId: 'tanam-urban',
    authDomain: 'tanam-urban.firebaseapp.com',
    databaseURL: 'https://tanam-urban-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanam-urban.firebasestorage.app',
    measurementId: 'G-7WJ47FTXYG',
  );
}
